# 公共登录数据
web_url: https://j2.sccpcloud.com/login/#/Login?clientId=visual_materials&redirectUrl=https%3A%2F%2Fvisualuat.sccpcloud.com%2Fmaterials%2F%23%2Fapp%2Fdynamic%2Flist%3Froute%3D
user: Mat001
pwd: Mima123!